
name: Test GitHub Actions

# Déclenchement du workflow
on:
  workflow_dispatch:           # à chaque push sur n'importe quelle branche
  pull_request:     # à chaque pull request

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Mini Test Job

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Afficher un message simple
      - name: Say Hello
        run: echo "Bonjour ! GitHub Actions fonctionne !"

      # 3️⃣ Test basique : vérifier si Python est installé
      - name: Check Python version
        run: python3 --version

      # 4️⃣ Test conditionnel simple
      - name: Test condition
        run: |
          if [ 1 -eq 1 ]; then
            echo "Le test passe ✅"
          else
            echo "Le test échoue ❌"
            exit 1
          fi
